id: P003202
initial_creation_type: ocr
source_metadata:
  id: bdr:W1229
  title: གསུང་འབུམ། ངག་དབང་བྱམས་པ
  author: ''
  volumes:
    bd3c2d1267f74a738f3506ed501f28e3:
      image_group_id: I1PD10380
      title: ''
      volume_number: 1
      total_pages: 702
    eaa14233696b4db2af734212d9ba208c:
      image_group_id: I1PD10381
      title: ''
      volume_number: 2
      total_pages: 708
    b6444b6469f042309734f52c74f7f188:
      image_group_id: I1PD10382
      title: ''
      volume_number: 3
      total_pages: 640
    0fa7db573fc440079be064f52281674e:
      image_group_id: I1PD10383
      title: ''
      volume_number: 4
      total_pages: 636
