id: I7737821A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:52:50+00:00'
last_modified: '2022-06-07T18:22:12.616007+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1229
  title: གསུང་འབུམ། ངག་དབང་བྱམས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BF57:
      image_group_id: I1PD10380
      title: ''
      total_pages: 702
      order: 1
      base_file: BF57.txt
    ADD4:
      image_group_id: I1PD10381
      title: ''
      total_pages: 708
      order: 2
      base_file: ADD4.txt
    FFFB:
      image_group_id: I1PD10382
      title: ''
      total_pages: 640
      order: 3
      base_file: FFFB.txt
    EF44:
      image_group_id: I1PD10383
      title: ''
      total_pages: 636
      order: 4
      base_file: EF44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
