id: I7737821A
legacy_id: P003202
ocr_import_info:
  bdrc_scan_id: W1229
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T11:48:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T13:36:05.125820+00:00'
last_modified: 2022-08-30 21:39:53.553189
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1229
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1229
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་བྱམས་པ།
  author: ཕུར་བུ་ལྕོག་ངག་དབང་བྱམས་པ།
statistics:
  ocr_word_mean_confidence_index: 0.7672452111894155
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I1PD10380:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD10380
      total_pages: 702
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD10380.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.736371914746769
    legacy_id: v001
  I1PD10383:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD10383
      total_pages: 636
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1PD10383.txt
    statistics:
      ocr_word_median_confidence_index: 0.9200000166893005
      ocr_word_mean_confidence_index: 0.8214414815967618
    legacy_id: v004
  I1PD10381:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD10381
      total_pages: 708
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1PD10381.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7312493179926526
    legacy_id: v002
  I1PD10382:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD10382
      total_pages: 640
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1PD10382.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7705755220713638
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
